# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in
main:

  #Introduce
  - name: 소개
    url: introduce
    identifier: introduce
    weight: 100
  - name: 자기소개
    url: whoami
    parent: introduce
    weight: 110
  - name: 취미
    url: hobby
    parent: introduce
    weight: 120

  #Skill
  - name: 스킬
    url: skill
    identifier: skill
    weight: 200
  - name: 프레임워크
    url: framework
    parent: skill
    weight: 210
  - name: 프로그래밍 언어
    url: programing_language
    parent: skill
    weight: 220

  #Experience
  - name: 경험
    url: experience
    identifier: experience
    weight: 300
  - name: 학위
    url: degree
    parent: experience
    weight: 310
  - name: 작업물
    url: work
    parent: experience
    weight: 320
  
  #Project
  - name: 프로젝트
    url: project
    identifier: project
    weight: 400
  - name: 개인프로젝트
    url: solo
    parent: project
    weight: 410
  - name: 팀프로젝트
    url: team
    parent: project
    weight: 420

  #License
  - name: 자격증
    url: license
    identifier: license
    weight: 500
  - name: IT자격증
    url: it
    parent: license
    weight: 510
  - name: 어학자격증
    url: language
    parent: license
    weight: 520


  #- name: Tour
  #  url: tour
  #  weight: 10
  #- name: News
  #  url: post
  #  weight: 20
  #
  #- name: Events
  #  url: event
  #  weight: 40
  #- name: Publications
  #  url: publication
  #  weight: 50
  #- name: Contact
  #  url: contact
  #  weight: 60
